handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /scripts
  static_dir: static/scripts

- url: /stylesheets
  static_dir: static/stylesheets

- url: /images
  static_dir: static/images
