handlers:
- url: /
  static_files: index.html index.htm readme.txt readme.markdown readme.md
  upload: .*

#- url: /verb/(.*)
#  static_files: verb/\1.html
#  upload: verb/\1.html

# =======
# CONTENT
# =======

- url: /getting-started/consumers(.*)
  static_files: getting-started/consumers.html
  upload: getting-started/consumers.html

- url: /getting-started/publishers(.*)
  static_files: getting-started/publishers.html
  upload: getting-started/publishers.html

- url: /getting-started(.*)
  static_files: getting-started/index.html
  upload: getting-started/index.html

# =====
# VERBS
# =====

- url: /verb/(favorite|follow|like|add-friend|join|play|post|rsvp|save|share|tag|update)(.*)
  static_files: verb/(favorite|follow|like|add-friend|join|play|post|rsvp|save|share|tag|update)/.html
  upload: verb/(favorite|follow|like|add-friend|join|play|post|rsvp|save|share|tag|update)/.html

- url: /verbs(.*)
  static_files: verbs/index.html
  upload: verbs/index.html

# =======
# OBJECTS
# =======

- url: /object-type/(article|audio|bookmark|comment|event|file|folder|group|list|note|person|photo|photo-album|place|playlist|product|review|service|song|status|video)(.*)
  static_files: object-type/(article|audio|bookmark|comment|event|file|folder|group|list|note|person|photo|photo-album|place|playlist|product|review|service|song|status|video)/
  upload: object-type/(article|audio|bookmark|comment|event|file|folder|group|list|note|person|photo|photo-album|place|playlist|product|review|service|song|status|video)/.html

- url: /(objects|object-types)(.*)
  static_files: object-types/index.html
  upload: object-types/index.html

# ====
# META
# ====


- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images
  
- url: /images/(.*)
  static_files: images/\1
  upload: images/(.*)