handlers:
- url: '/'
  static_files: 'index.html index.htm readme.txt readme.markdown readme.md'
  upload: '.*'

- url: '/'
  static_files: '/'

- url: /scripts
  static_dir: static/scripts

- url: /stylesheets
  static_dir: static/stylesheets

- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/(.*)