handlers:
- url: /
  static_files: index.html index.htm readme.txt readme.markdown readme.md
  upload: .*

#- url: /verb
#  static_dir: verb

#- url: /verb/(.*)
#  static_files: verb/\1.html
#  upload: verb/\1.html

# =======
# CONTENT
# =======

- url: /getting-started/consumers(.*)
  static_files: getting-started/consumers.html
  upload: getting-started/consumers.html

- url: /getting-started/publishers(.*)
  static_files: getting-started/publishers.html
  upload: getting-started/publishers.html

- url: /getting-started(.*)
  static_files: getting-started/index.html
  upload: getting-started/index.html

# =====
# VERBS
# =====

- url: /verb/post(.*)
  static_files: verb/post.html
  upload: verb/post.html

- url: /verbs(.*)
  static_files: verbs/index.html
  upload: verbs/index.html

# =======
# OBJECTS
# =======

- url: /object-type/photo(.*)
  static_files: object-type/photo.html
  upload: object-type/photo.html

- url: /object-types(.*)
  static_files: object-types/index.html
  upload: object-types/index.html



# ====
# META
# ====


- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images
  
- url: /images/(.*)
  static_files: images/\1
  upload: images/(.*)