handlers:
- url: /
  static_files: index.html index.htm readme.txt readme.markdown readme.md
  upload: .*

#- url: /verb
#  static_dir: verb

#- url: /verb/(.*)
#  static_files: verb/\1.html
#  upload: verb/\1.html

# =====
# VERBS
# =====

- url: /verb/post
  static_files: verb/post.html
  upload: verb/post.html

# =======
# OBJECTS
# =======


- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images
  
- url: /images/(.*)
  static_files: images/\1
  upload: images/(.*)